### ISSUE TITLE
Consolidate Puck sensors and controls into single accessory

### ISSUE THREAD

**Issue by HammerAce42** [bassrock/homebridge-flair#2]
I think the Homekit UI would be cleaner if the humidity and temperature sensor readings from the Puck were consolidated with the thermostat control. I have a lot Homekit accessories, so am always looking to keep the UI in the HomeKit app as clear as possible.

**Comment by bassrock** [comment]
Yea I can see how that makes sense. However I did it this way because of how the API is designed. The thermostats are actually Flair rooms. 

Since in flair you set the temperature of the room and a room could have multiple Puck sensors.

**Comment by HammerAce42** [comment]
Interesting - I suspect that's a fairly unusual case though. Perhaps make it an option via the config file?

**Comment by bassrock** [comment]
Perhaps a better way would be to give the option to disable the puck sensors since the "Room Thermostats" also provide the same information in the API aggregated with a rolling 5 minute average.

**Comment by HammerAce42** [comment]
Yes, providing a way to disable the puck sensors seems like a good compromise.

Thanks!

**Comment by bassrock** [comment]
Just pushed 1.0.2 that now has this option.
