### ISSUE TITLE
Homebridge Beta warns that firmware version needs to be a string, not a number

### ISSUE THREAD

**Issue by HammerAce42** [bassrock/homebridge-flair#51]
Running the plugin in the latest homebridge beta version generates this warning, and indicates that this will start returning an error in future versions.

**Comment by HammerAce42** [comment]
Here is the specific message from the log: Received warning for the plugin 'homebridge-flair' from the characteristic 'Firmware Revision': characteristic was supplied illegal value: number instead of string. Supplying illegal values will throw errors in the future!

**Comment by bassrock** [comment]
This has been merged. I had to slightly adjust it in the latest version.
