### ISSUE TITLE
Read-Only Flair Sensors

### ISSUE THREAD

**Issue by nickv2002** [bassrock/homebridge-flair#59]
Thanks for the work you've done on this plugin! It works really well.

### Feature enhancement Request
I would like to expose all the Flair temperatures as read-only sensors instead of adjustable thermostats. (This is mostly because of the way HomeKit interacts with Siri, if there are multiple thermostats I have to tell Siri which one I meant, and I never want to actually adjust the Flair one).

Would it be possible to have an **alternate mode where the Flair pucks are presented as non-adjustable sensors** instead?

Thanks again!

**Comment by bassrock** [comment]
@nickv2002 this has been released in 1.2.0, you can select hideRoomThermostats in the homebridge config gui after you update.

**Comment by nickv2002** [comment]
Thanks @bassrock - this should work well. 👍
