### ISSUE TITLE
Logic for auto

### ISSUE THREAD

**Issue by mikeknoop** [bassrock/homebridge-flair#6]
https://github.com/bassrock/homebridge-flair/blob/b7ea8b3370c918042f6a51ce2b4c39b48eb26d37/src/roomPlatformAccessory.ts#L91-L95

Why do you override the "auto" setting by setting "cool" for the structure on [these lines above](https://github.com/bassrock/homebridge-flair/blob/b7ea8b3370c918042f6a51ce2b4c39b48eb26d37/src/roomPlatformAccessory.ts#L91-L95
) (and in `getCurrentHeatingCoolingStateFromStructure`)?

This seems like a bug to me? In the Home app you choose "auto" which sets the state in the Flair app to "cool".

**Comment by bassrock** [comment]
@mikeknoop thanks for the report! I just released 1.0.6 that should fix this
