### ISSUE TITLE
Not installing properly with HOOBS? 

### ISSUE THREAD

**Issue by SRamsdell1** [bassrock/homebridge-flair#7]
I get a successful plugin installation message when installing, But no "Accessories" appear, and log file contains following tow errors ? 
6/2/2020, 1:38:26 PM The requested platform "Flair" was not registered by any plugin.
6/2/2020, 1:38:26 PM Your config.json is requesting the platform "Flair" which has not been published by any installed plugins.

I've tried uninstall - reinstall, and rollback to backup - install ... same results each time.

**Comment by bassrock** [comment]
Can you post what your config looks like with your credentials redacted?

**Comment by SRamsdell1** [comment]
Upgraded to 1.0.6 - same issue.
Change "platform": "Flair" to "flair" - same issue.

Any other suggestions ?

**Comment by SRamsdell1** [comment]
FWIW, the issue seems to be compatibility with the way HOOBS installs plugins.  The same configuration file when installed on another homebride service works fine.

I've also not figured out how to force temp to be in F yet and it would be awesome if Battery level on vents and offline could be pulled back (this is a miss with Flair in general to me).

**Comment by arsoneffect** [comment]
HOOBS does not allow for -g installs (global).

Look at this thread from the support team for more info:

https://www.reddit.com/r/HOOBS/comments/epl0xn/the_requested_accessory_was_not_registered_by_any/fekevz1?utm_source=share&utm_medium=web2x

**Comment by arsoneffect** [comment]
> FWIW, the issue seems to be compatibility with the way HOOBS installs plugins. The same configuration file when installed on another homebride service works fine.
> 
> I've also not figured out how to force temp to be in F yet and it would be awesome if Battery level on vents and offline could be pulled back (this is a miss with Flair in general to me).

HOOBS does not allow for -g installs (global).

Look at this thread from the support team for more info:

https://www.reddit.com/r/HOOBS/comments/epl0xn/the_requested_accessory_was_not_registered_by_any/fekevz1?utm_source=share&utm_medium=web2x

**Comment by bassrock** [comment]
Looks like this is how hoobs works. https://github.com/hoobs-org/HOOBS/wiki/4.0-Plugins#how-plugins-work

You will need to follow instructions there to install it.

**Comment by arsoneffect** [comment]
Looks like there’s a way to get it certified:
https://hoobs.org/?download=143

**Comment by arsoneffect** [comment]
Any updates?

**Comment by TechBLT** [comment]
Hi, I wrote about having the issue above on reddit in the Hoobs sub and one of the Hoobs people responded and submitted a pull request here on your github with the necessary changes to make it work with Hoobs. Can you please merge in the change? Thanks.

**Comment by bassrock** [comment]
Hi the pr was just merged and released with https://github.com/bassrock/homebridge-flair/pull/10
